export enum NavigationRoute {
  SETTINGS = 'settings',

  BARCODE_CAPTURE = 'barcode-capture',
  SYMBOLOGIES = 'symbologies',
  COMPOSITE_TYPES = 'composite-types',
  LOCATION_SELECTION = 'location-selection',
  LOCATION_SELECTION_WIDTH = 'width',
  LOCATION_SELECTION_HEIGHT = 'height',
  LOCATION_SELECTION_SIZE = 'size',
  FEEDBACK = 'feedback',
  CODE_DUPLICATE_FILTER = 'code-duplicate-filter',

  CAMERA = 'camera',

  VIEW = 'view',
  SCAN_AREA = 'scan-area',
  SCAN_AREA_MARGIN_TOP = 'top',
  SCAN_AREA_MARGIN_RIGHT = 'right',
  SCAN_AREA_MARGIN_BOTTOM =  'bottom',
  SCAN_AREA_MARGIN_LEFT = 'left',
  POINT_OF_INTEREST = 'point-of-interest',
  POINT_OF_INTEREST_X = 'x',
  POINT_OF_INTEREST_Y = 'y',
  OVERLAY = 'overlay',
  VIEWFINDER = 'viewfinder',
  VIEWFINDER_WIDTH = 'width',
  VIEWFINDER_HEIGHT = 'height',
  VIEWFINDER_LASERLINE_WIDTH = 'laserline-width',
  VIEWFINDER_LASERLINE_STYLE = 'laserline-style',
  LOGO = 'logo',
  LOGO_X = 'x',
  LOGO_Y = 'y',
  CONTROLS = 'controls',
  GESTURES = 'gestures',

  RESULT = 'result',
}
