
export enum SettingsFieldName {

  // barcode capture

  // barcode capture - location selection
  LOCATION_SELECTION_TYPE = 'LOCATION_SELECTION_TYPE',
  LOCATION_SELECTION_SIZE_SPECIFICATION = 'LOCATION_SELECTION_SIZE_SPECIFICATION',
  LOCATION_SELECTION_WIDTH = 'LOCATION_SELECTION_WIDTH',
  LOCATION_SELECTION_WIDTH_ASPECT = 'LOCATION_SELECTION_WIDTH_ASPECT',
  LOCATION_SELECTION_HEIGHT = 'LOCATION_SELECTION_HEIGHT',
  LOCATION_SELECTION_HEIGHT_ASPECT = 'LOCATION_SELECTION_HEIGHT_ASPECT',
  LOCATION_SELECTION_SIZE = 'LOCATION_SELECTION_SIZE',

  // barcode capture - code duplicate filter
  CODE_DUPLICATE_FILTER = 'CODE_DUPLICATE_FILTER',

  // barcode capture - composite types
  COMPOSITE_TYPES = 'COMPOSITE_TYPES',

  // barcode capture - feedback
  FEEDBACK_SOUND = 'FEEDBACK_SOUND',
  FEEDBACK_VIBRATION = 'FEEDBACK_VIBRATION',

  // camera
  CAMERA_POSITION = 'CAMERA_POSITION',
  DESIRED_TORCH_STATE = 'DESIRED_TORCH_STATE',
  MAX_FRAME_RATE = 'MAX_FRAME_RATE',
  PREFERRED_RESOLUTION = 'PREFERRED_RESOLUTION',
  ZOOM_FACTOR = 'ZOOM_FACTOR',
  ZOOM_GESTURE_ZOOM_FACTOR = 'ZOOM_GESTURE_ZOOM_FACTOR',
  FOCUS_RANGE = 'FOCUS_RANGE',
  FOCUS_GESTURE_STRATEGY = 'FOCUS_GESTURE_STRATEGY',

  // view

  SCAN_AREA_MARGIN_TOP = 'SCAN_AREA_MARGIN_TOP',
  SCAN_AREA_MARGIN_RIGHT = 'SCAN_AREA_MARGIN_RIGHT',
  SCAN_AREA_MARGIN_BOTTOM = 'SCAN_AREA_MARGIN_BOTTOM',
  SCAN_AREA_MARGIN_LEFT = 'SCAN_AREA_MARGIN_LEFT',
  SCAN_AREA_GUIDES = 'SCAN_AREA_GUIDES',

  POINT_OF_INTEREST_X = 'POINT_OF_INTEREST_X',
  POINT_OF_INTEREST_Y = 'POINT_OF_INTEREST_Y',

  BRUSH = 'BRUSH',

  VIEWFINDER_TYPE = 'VIEWFINDER_TYPE',
  VIEWFINDER_SIZE_SPECIFICATION = 'VIEWFINDER_SIZE_SPECIFICATION',
  VIEWFINDER_WIDTH = 'VIEWFINDER_WIDTH',
  VIEWFINDER_WIDTH_ASPECT = 'VIEWFINDER_WIDTH_ASPECT',
  VIEWFINDER_SHORTER_DIM = 'VIEWFINDER_SHORTER_DIM',
  VIEWFINDER_ASPECT_RATIO = 'VIEWFINDER_ASPECT_RATIO',
  VIEWFINDER_HEIGHT = 'VIEWFINDER_HEIGHT',
  VIEWFINDER_HEIGHT_ASPECT = 'VIEWFINDER_HEIGHT_ASPECT',
  VIEWFINDER_LASERLINE_WIDTH = 'VIEWFINDER_LASERLINE_WIDTH',
  VIEWFINDER_LASERLINE_STYLE = 'VIEWFINDER_LASERLINE_STYLE',
  VIEWFINDER_AIMER_FRAME_COLOR = 'VIEWFINDER_AIMER_FRAME_COLOR',
  VIEWFINDER_AIMER_DOT_COLOR = 'VIEWFINDER_AIMER_DOT_COLOR',
  VIEWFINDER_STYLE = 'VIEWFINDER_STYLE',
  VIEWFINDER_LINE_STYLE = 'VIEWFINDER_LINE_STYLE',
  VIEWFINDER_DIMMING = 'VIEWFINDER_DIMMING',
  VIEWFINDER_COLOR = 'VIEWFINDER_COLOR',
  VIEWFINDER_ENABLED_COLOR = 'VIEWFINDER_ENABLED_COLOR',
  VIEWFINDER_DISABLED_COLOR = 'VIEWFINDER_DISABLED_COLOR',

  LOGO_ANCHOR = 'LOGO_ANCHOR',
  LOGO_X = 'LOGO_X',
  LOGO_Y = 'LOGO_Y',

  TORCH_BUTTON = 'TORCH_BUTTON',

  TAP_TO_FOCUS = 'TAP_TO_FOCUS',
  SWIPE_TO_ZOOM = 'SWIPE_TO_ZOOM',

  // result
  CONTINUOUS_SCANNING = 'CONTINUOUS_SCANNING',
}
