export enum SettingsFieldType {
  TOGGLE = 'TOGGLE',
  NUMBER = 'NUMBER',
  UNIT_NUMBER = 'UNIT_NUMBER',
  SLIDER = 'SLIDER',
  SELECT = 'SELECT',
  FLAT_SELECT = 'FLAT_SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
}
